server:
  port: 3333

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/db_gesproplus
        username: admin
        password: azerty01**
        driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Africa/Casablanca
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  liquibase:
      change-log: classpath:db/changelog/liquibase-changelog.yaml
      enabled: true

  security:
    enabled: true
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE"
    allowed-headers: "Content-Type,Authorization"
    exposed-headers: "Authorization,Content-Disposition"
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bdcc_realm
          jwk-set-uri: http://localhost:8089/realms/bdcc_realm/protocol/openid-connect/certs


