server:
  port: 3333

spring:
  profiles:
    active: dev
  security:
    enabled: true
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE"
    allowed-headers: "Content-Type,Authorization"
    exposed-headers: "Authorization,Content-Disposition"
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bdcc_realm
          jwk-set-uri: http://localhost:8080/realms/bdcc_realm/protocol/openid-connect/certs


