spring:
  datasource:
    url: jdbc:h2:mem:db_gesproplus_test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: super-secret-key-must-be-32-bytes!



